<?php

/*  Copyright 2013, Electric Paper Evaluationssysteme GmbH
 
    This file is part of EvaExam HTML Report
  
    EvaExam HTML Report is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    EvaExam HTML is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with EvaExam HTML Report.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
 
/**
 * Partial Helper for building participant results table 
 * @author Mario Diaz
 */

    $qPageCounter = 1;
    $nextPageBreak = $this->maxQuestionsToDisplay;
    
    for ($qCounter = 1;  $qCounter <= $this->totalQuestions ; $qCounter++) 
    {     
          
          
          if ($qCounter > $nextPageBreak) 
          {
              $nextPageBreak = $nextPageBreak + $this->maxQuestionsToDisplay;
              $qPageCounter++;
          }
          
          
          if ($qCounter <= $this->maxQuestionsToDisplay)
          {
              if ($this->isHeader)
              {
                  echo  '<th class="question_page_1 display">'.$qCounter.'</th>';
              }
              else
              {
                  echo  '<td class="question_page_1 display">'.$this->questionArray[$qCounter - 1 ].'</td>';
              }
              
          }
          else
          {   if ($this->isHeader)
              {
                 echo '<th class="question_page_'.$qPageCounter.' hidden">'.$qCounter.'</th>';
              }
              else
              {
                  echo '<td class="question_page_'.$qPageCounter.' hidden">'.$this->questionArray[$qCounter - 1 ].'</td>';
              }
                
          }
          
        
    } ?>
    </tr>
