<?php

/*  Copyright 2013, Electric Paper Evaluationssysteme GmbH
 
    This file is part of EvaExam HTML Report
  
    EvaExam HTML Report is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    EvaExam HTML is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with EvaExam HTML Report.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * Language file that contains english text for the EvaExam HTML Report.
 * @author Mario Diaz
 */

return $english = array(
    'S_EXAM_NAME'         => 'Exam',
    'S_EXAMINER_NAME'     => 'Examiner',
    'S_RESPONSE_RATE'     => 'Response Rate',
    'S_FORM_NAME'         => 'Form Name',
    'S_PARTICIPANT_ID'    => 'Participant Id',
    'S_GRADE'             => 'Grade',
    'S_TYPE'              => 'Format',
    'S_EXAM_REPORT_TITLE' => 'Exam Report',
    'S_QUESTIONS_RESULT_TITLE'=> 'Questions Results',
    'S_GRADE_REPORT_TITLE' => 'Grade Report',
    'S_GENERAL_STATISTICS_TITLE' => 'General Statistics',
    'S_PARTICIPANT_ID_HEADER'    => 'Participant Id',
    'S_TOTAL_POINTS'             => 'Points',
    'S_NOTE'                     => 'Note',
    'S_PASSED'                   => 'Passed',
    'S_IS_APPROVED'              => 'Yes',
    'S_IS_FAILED'                => 'No',
    'S_N_PARTICIPANTS'           => 'Participants',
    'S_REACHABLE_POINTS'          => 'Reachable Points',
    'S_MEAN'                     => 'Mean',
    'S_MAX_POINTS'               => 'Max. Points',
    'S_MIN_POINTS'               => 'Min. Points',
    'S_MEDIAN'                   => 'Median',
    'S_STANDART_DEVIATION'       => 'Standart Devaition',
    'S_PERCENTAGE'               => 'Percentage',
    'S_STATUS_RESULT'            => 'Result',
    'S_FAILED'                   => 'Failed',
    'S_FILTER_SECTION_TITLE'     => 'Content Filters',
    'S_FILTER_SHOW_ALL_LABEL'    => 'Show All',
    'S_FILTER_BY_GRADE_LABEL'    => 'By Grade',
    'S_FILTER_BY_PASSED_LABEL'   => 'By Passed/Failed',
    'S_BACK'                     => 'Back',
    'S_NEXT'                     => 'Next',
    'S_SCORE_RANGE'              => 'Min.Percentage',
    'S_THRESHOLD_GRADE_POINTS'   => 'Approval Threshold - Points',
    'S_THRESHOLD_GRADE_PERCENTAGE'   => 'Approval Threshold - Percentage',
    'S_THRESHOLD_GRADE_NAME'     => 'Min Approval Grade',
    'S_PARTICIPANTS_PERCENTAGE'  => 'Participants Percentage',
	'S_EXAM_REPORT'				 => 'HTML Report',
	'S_EXAM_NAME'				 => 'Exam',
	'S_EXAM_ID'					 => 'ID',
	'S_EXAM_COUNT'				 => 'Count',
	'S_MENU_ACTIONS'			 => 'Actions',
	'S_MENU_SETIINGS'			 => 'Settings',
	'S_MENU_INFOS'				 => 'Info'
	
)

?>
